#+TITLE: Math
#+PROPERTY: ANKI_DECK Math

* Elements of Algebra - Leonhard Euler
:LOGBOOK:
CLOCK: [2020-07-28 Tue 11:22]--[2020-07-28 Tue 13:16] =>  1:54
CLOCK: [2020-07-28 Tue 09:02]--[2020-07-28 Tue 09:52] =>  0:50
CLOCK: [2020-07-11 Sat 12:47]--[2020-07-11 Sat 13:47] =>  1:00
CLOCK: [2020-07-11 Sat 10:57]--[2020-07-11 Sat 11:57] =>  1:00
CLOCK: [2020-07-11 Sat 09:39]--[2020-07-11 Sat 10:40] =>  1:01
CLOCK: [2020-07-10 Fri 13:23]--[2020-07-10 Fri 14:23] =>  1:00
CLOCK: [2020-07-10 Fri 11:17]--[2020-07-10 Fri 12:17] =>  1:00
CLOCK: [2020-07-10 Fri 09:57]--[2020-07-10 Fri 10:58] =>  1:01
CLOCK: [2020-07-10 Fri 08:30]--[2020-07-10 Fri 09:30] =>  1:00
CLOCK: [2020-07-09 Thu 12:15]--[2020-07-09 Thu 13:16] =>  1:01
CLOCK: [2020-07-09 Thu 10:57]--[2020-07-09 Thu 11:00] =>  1:03
CLOCK: [2020-07-09 Thu 09:29]--[2020-07-09 Thu 10:30] =>  1:01
:END:

** Chapter II – Explanation of the Signs + Plus and – Minus
*** Natural Numbers
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525419651
:END:

**** Text

math: {{c1::Natural Numbers}} = {{c2::0, 1, 2, ...}} or {{c2::1, 2, ...}}

*** Natural Numbers Including 0
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525419791
:END:

**** Text

math: {{c1::N_0}} = {{c1::N^0}} = {{c1:: N \cup {0} }} = {{c2:: {0, 1, 2, …} }}

*** Natural Numbers Excluding 0
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525419952
:END:

**** Text

math: {{c1:: N^{*} }} = {{c1:: N^{+} }} = {{c1:: N_{1} }} = {{c1:: N_{>0} }} = {{c1:: N \ {0} }} =
{{c2:: {1, 2, 3, …} }}

** Chapter III – Of the Multiplication of Simple Quantities
*** Associative Property
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525420110
:END:

**** Text

math: f is {{c1::Associative}} if {{c2::f(f(a, b), c) = f(a, f(b, c))}}

*** Commutative Property
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525420309
:END:

**** Text

math: f is {{c1::Commutative}} if {{c2::f(a, b) = f(b, a)}}

** Chapter VII – Of Fractions in General
*** Numerator and Denominator
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1629032661663
:END:

**** Text

math: In a/b, a is the {{c1::Numerator}} or {{c1::Dividend}} and b is the
{{c1::Denominator}} or {{c1::Divisor}}

*** Fraction Description
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525421223
:END:

**** Text

math: 7/3 is read as {{c1::Seven Thirds}}

*** Improper Fraction
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525421371
:END:

**** Text

math: a/b is {{c1::an Improper}} fraction if {{c2::a >= b}}

*** Proper Fraction
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525421537
:END:

**** Text

math: a/b is {{c1::a Proper}} fraction if {{c2::a < b}}

*** Mixed Number
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525421657
:END:

**** Text

math: A {{c1::Mixed Number}} is {{c2::the sum of a non-zero integer and a proper fraction}}

*** Mixed Number Notation
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525421805
:END:

**** Text

math: A {{c1::Mixed Number}} is noted as {{c2::$a\frac{b}{c}$}}

** Chapter VIII – Of the Properties of Fractions
*** Multiplying the Numerator and Denominator
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525421965
:END:

**** Text

math: proof: ma/mb = a/b
{{c1::
#+BEGIN_SRC
Extract m/m out of the fraction:
ma/mb = a/b * m/m
      = a/b * 1
      = a/b
#+END_SRC
}}

** Questions for Practice

1. Reduce $\frac{cx + x^2}{ca^2 + ax^2}$ to its lowest terms.

   \begin{align}
   \frac{cx + x^2}{ca^2 + ax^2} &= \frac{x(c + x)}{a^2(c + x)} \\
   &= \frac{x}{a^2}
   \end{align}

2. Reduce $\frac{x^3 - b^2x}{x^2 + 2bx + b^2}$ to its lowest terms.

   Note: I had a hard time finding this one because I didn't immediately recognize $x^2 - b^2 = (x +
   b)(x - b)$.

   \begin{align}
   \frac{x^3 - b^2x}{x^2 + 2bx + b^2} &= \frac{x(x^2 - b^2)}{(x + b)^2} \\
   &= \frac{x(x + b)(x - b)}{(x + b)^2} \\
   &= \frac{x(x - b)}{x + b} \\
   &= \frac{x^2 - bx}{x + b}
   \end{align}

3. Reduce $\frac{x^4 - b^4}{x^2 + 2bx + b^2}$ to its lowest terms.

   Note: I had a hard time finding this one because I didn't immediately think of factoring $x^3$ in
   the denominator.

   \begin{align}
   \frac{x^4 - b^4}{x^2 + 2bx + b^2} &= \frac{(x^2 + b^2)(x^2 - b^2)}{x^3(x^2 - b^2)} \\
   &= \frac{x^2 + b^2}{x^3}
   \end{align}

4. Reduce $\frac{x^2 - y^2}{x^4 - y^4}$ to its lowest terms.

   \begin{align}
   \frac{x^2 - y^2}{x^4 - y^4} &= \frac{(x + y)(x - y)}{(x^2 + y^2)(x^2 - y^2)} \\
   &= \frac{(x + y)(x - y)}{(x^2 + y^2)(x + y)(x - y))} \\
   &= \frac{1}{x^2 + y^2}
   \end{align}

5. Reduce $\frac{a^4 - x^4}{a^3 - a^2x - ax^2 + x^3}$ to its lowest terms.

   \begin{align}
   \frac{a^4 - x^4}{a^3 - a^2x - ax^2 + x^3} &= \frac{(a^2 + x^2)(a^2 - x^2)}{(a^2 - x^2)(a - x)} \\
   &= \frac{a^2 + x^2}{a - x}
   \end{align}

6. Reduce $\frac{5a^5 + 10a^4x + 5a^3x^2}{a^3x + 2a^2x^2 + 2ax^3 + x^4}$ to its lowest terms.

   \begin{align}
   \frac{5a^5 + 10a^4x + 5a^3x^2}{a^3x + 2a^2x^2 + 2ax^3 + x^4} &= \frac{5a^3(a^2 + 2ax + x^2)}{(a + x)(a^2x + ax^2 + x^2)} \\
   &= \frac{5a^3(a + x)^2}{(a + x)(a^2x + ax^2 + x^2)} \\
   &= \frac{5a^3(a + x)}{a^2x + ax^2 + x^2} \\
   &= \frac{5a^4 + 5a^3x}{a^2x + ax^2 + x^2}
   \end{align}

** Chapter IX – Of the Addition and Subtraction of Fractions
*** Adding Fractions With The Same Denominator
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525422180
:END:

**** Text

math: a/c + b/c = {{c1::(a + b)/c}} because
{{c1::
#+BEGIN_SRC
a/c + b/c = a * 1/c + b * 1/c
          = (a + b) * 1/c
          = (a + b)/c
#+END_SRC
}}

** Questions for Practice

1. Reduce $\frac{2x}{a}$ and $\frac{b}{c}$ to a common denominator.

   \begin{align}
   \frac{2x}{a} &= \frac{2cx}{ac} \\
   \frac{b}{c} &= \frac{ab}{ac}
   \end{align}

2. Reduce $\frac{a}{b}$ and $\frac{a + b}{c}$ to a common denominator.

   \begin{align}
   \frac{a}{b} &= \frac{ac}{bc} \\
   \frac{a + b}{c} &= \frac{ab + b^2}{bc}
   \end{align}

3. Reduce $\frac{3x}{2a}$, $\frac{2b}{3c}$ and $d$ to a common denominator.

   \begin{align}
   \frac{3x}{2a} &= \frac{9cx}{6ac} \\
   \frac{2b}{3c} &= \frac{4ab}{6ac} \\
   d &= \frac{6acd}{6ac}
   \end{align}

4. Reduce $\frac{3}{4}$, $\frac{2x}{3}$ and $a + \frac{2x}{a}$ to a common
   denominator.

   \begin{align}
   \frac{3}{4} &= \frac{9a}{12a} \\
   \frac{2x}{3a} &= \frac{8ax}{12a} \\
   a + \frac{2x}{a} &= \frac{12a^2 + 24x}{12a}
   \end{align}

5. Reduce $\frac{1}{2}$, $\frac{a^2}{3}$ and $\frac{x^2 + a^2}{x + a}$ to a
   common denominator.

   \begin{align}
   \frac{1}{2} &= \frac{3(x + a)}{6(x + a)} \\
   \frac{a^2}{3} &= \frac{2a^2(x + a)}{6(x + a)} \\
   \frac{6(x^2 + a^2)}{x + a} &= \frac{6(x^2 + a^2)}{6(x + a)}
   \end{align}

6. Reduce $\frac{b}{2a^2}$, $\frac{c}{2a}$ and $\frac{d}{a}$ to a common
   denominator.

   \begin{align}
   \frac{b}{2a^2} &= \frac{b}{2a^2} \\
   \frac{c}{2a} &= \frac{ac}{2a^2} \\
   \frac{d}{a} &= \frac{2ad}{2a^2}
   \end{align}

** Chapter X – Of the Multiplication and Division of Fractions
*** (a/b)/c = a/bc
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525422328
:END:

**** Text

math: (a/b)/c = {{c1::a/bc}}

*** Proof of (a/b)/c = a/bc
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525422585
:END:

**** Text

math: proof: (a/b)/c = a/bc
{{c1::
#+BEGIN_SRC
(a/b)/c = a/b * 1/c
        = a/bc
#+END_SRC
}}

*** Proof of 1/ab = 1/a * 1/b
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525423160
:END:

**** Text

math: proof: 1/ab = 1/a * 1/b
{{c1::
#+BEGIN_SRC
1/ab is the inverse of ab, so
ab * 1/ab must be equal to 1
ab * (1/a * 1/b) = a * 1/a * b * 1/b
                 = 1 * 1
                 = 1
#+END_SRC
}}

*** Proof of (a/b) * (c/d) = ab/cd
:PROPERTIES:
:Source: http://mathforum.org/library/drmath/view/63841.html
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525423325
:END:

**** Text

math: proof: (a/b) * (c/d) = ac/bd
{{c1::
#+BEGIN_SRC
(a/b) * (c/d) = a * 1/b * c * 1/d
              = a * c * 1/b * 1/d
              = a * c * 1/bd (multiplicative inverse is the product of multiplicative inverses)
              = ac/bd
#+END_SRC
}}

* OpenStax - Prealgebra 2e
:LOGBOOK:
CLOCK: [2020-08-12 Wed 10:20]--[2020-08-12 Wed 11:20] =>  1:00
CLOCK: [2020-08-04 Tue 08:12]--[2020-08-04 Tue 10:12] =>  2:00
CLOCK: [2020-07-31 Fri 16:21]--[2020-07-31 Fri 18:21] =>  2:00
CLOCK: [2020-07-31 Fri 13:44]--[2020-07-31 Fri 15:45] =>  2:01
CLOCK: [2020-07-22 Wed 14:00]--[2020-07-22 Wed 15:01] =>  1:01
CLOCK: [2020-07-22 Wed 15:09]--[2020-07-22 Wed 16:09] =>  1:00
CLOCK: [2020-07-22 Wed 11:14]--[2020-07-22 Wed 12:17] =>  1:03
CLOCK: [2020-07-21 Tue 09:44]--[2020-07-21 Tue 13:44] =>  4:00
:END:

** 2.5 Prime Factorization and the Least Common Multiple
*** Least Common Multiple
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525423523
:END:

**** Text

math: {{c1:: ~least_common_multiple(a,b)~ }} = {{c2::the smallest number that is divisible by both a and b}}

*** Least Common Multiple Example
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525423646
:END:

**** Text

math: ~least_common_multiple(4, 6)~ = {{c1::12}}

*** Greatest Common Divisor
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525423796
:END:

**** Text

math: {{c1:: ~greatest_common_divisor(a,b)~ }} = {{c2::the greatest number that divides both a and b}}

*** Greatest Common Divisor Example
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525423971
:END:

**** Text

math: ~greatest_common_divisor(8, 12)~ = {{c1::4}}

*** Greatest Common Divisor Use
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525424108
:END:

**** Text

math: To reduce a fraction {{c1::divide the numerator and denominator by their greatest common divisor}}

** 4.2 Multiply and Divide Fractions
*** Irreducible Fraction
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525424270
:END:

**** Text

math: a/b is an Irreducible Fraction if {{c1:: ~greatest_common_divisor(a, b) = 1~ }}

*** Irreducible Fraction
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525424697
:END:

**** Text

math: {{c1::Irreducible Fraction}} aka {{c2::Simplified Fraction}}

*** Multiplicative Inverse aka Reciprocal
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525424927
:END:

**** Text

math: {{c1::Multiplicative Inverse}} aka {{c2::Reciprocal}}

*** Multiplicative Inverse Definition
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525425102
:END:

**** Text

math: Y is the {{c1::Muliplicative Inverse}} of X if {{c2::X * Y = 1}}

*** The Muliplicative Inverse of a/b
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525425300
:END:

**** Text

math: The multiplicative inverse of {{c1::a/b}} is {{c2::b/a}}

*** Proof of the Muliplicative Inverse of a/b is b/a
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525425491
:END:

**** Text

math: proof: The multiplicative inverse of a/b is b/a:
{{c1::
#+BEGIN_SRC
State as an equation, and then cancel the denominator:
a/b * X = 1
      X = 1/(a/b)
      X = 1/(a/b) * 1
      X = 1/(a/b) * (b/a)/(b/a)
      X = (b/a)/(ab/ab)
      X = (b/a)/1 (identity property of division)
      X = b/a
#+END_SRC
}}

*** 1/(a/b) = b/a
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525425676
:END:

**** Text

math: 1/(a/b) = {{c1::b/a}}

*** Proof of 1/(a/b) = b/a
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525425867
:END:

**** Text

math: proof: 1/(a/b) = b/a:
{{c1::
#+BEGIN_SRC
Cancel the demoninator by multipying the numerator and the denominator by b/a:
1/(a/b) = 1/(a/b) * 1
        = 1/(a/b) * (b/a)/(b/a)
        = (b/a)/(ab/ab)
        = (b/a)/1
        = b/a
#+END_SRC
}}

*** (a/b)/(c/d) = ad/bc
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525426004
:END:

**** Text

math: (a/b)/(c/d) = {{c1::ad/bc}}

*** Proof of (a/b)/(c/d) = ad/bc
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525426477
:END:

**** Text

math: proof: (a/b)/(c/d) = ad/bc
{{c1::
#+BEGIN_SRC
(a/b)/(c/d) = (a/b) * 1/(c/d) (division is multiplication by inverse)
            = (a/b) * (d/c) (inverse)
            = ad/bc
#+END_SRC
}}

** 5.3 Decimals and Fractions
*** Repeating Decimal
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525426787
:END:

**** Text

math: A Repeating Decimal is a {{c1::Decimal Number in which the last digits repeat endlessly}}

*** Repeating Decimal Notation
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525426962
:END:

**** Text

math: A Repeating Decimal is written as {{c1::$X.Y\overline{Z}$}}

** 5.5 Averages and Probability
*** Mean aka Arithmetic Average
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525427098
:END:

**** Text

math: {{c1::Mean}} aka {{c2::Arithmetic Average}}

*** Mean Formula
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525427212
:END:

**** Text

math: {{c1::Mean}} = {{c2::Sum of all the Values / The Number of Values}}

*** Median Formula
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525427362
:END:

**** Text

math: {{c1::Median}} = {{c2::The middle value when there is an odd number of them. The mean of the two
middle values otherwise}}

*** Mode Formula
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525427575
:END:

**** Text

math: {{c1::Mode}} = {{c2::The number with the highest frequency}}

*** Probability Formula
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525427711
:END:

**** Text

math: Probability Formula = {{c1::Number of Favorable Outcomes/Number of Outcomes}}

** 5.6 Ratios and Rate
*** Ratio
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525427871
:END:

**** Text

math: A {{c1::Ratio}} is {{c2::a fraction of two numbers with the same unit}}

*** Rate
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525428272
:END:

**** Text

math: A {{c1::Rate}} is {{c2::a fraction of two numbers with different units}}

*** Unit Rate
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525428426
:END:

**** Text

math: A {{c1::Unit Rate}} is {{c2::a Rate with a denominator of 1}}

** 5.7 Simplify and Use Square Roots
*** Perfect Square
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525428663
:END:

**** Text

math: A {{c1::Perfect Square}} is a {{c2::Square of an integer}}

*** Radical Sign aka Root Symbol
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525428854
:END:

**** Text

math: {{c1::Radical Sign}} aka {{c2::Root Symbol}}

*** Principal Root
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525429056
:END:

**** Text

math: $\sqrt{x^2}$ = {{c1::|x|}}

** 7.1 Rational and Irrational Numbers
*** Rational Numbers
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525429236
:END:

**** Text

math: {{c1::Rational Numbers}} are {{c2::numbers that can be expressed as a fraction of two integers}}

*** Irrational Numbers
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525429384
:END:

**** Text

math: {{c1::Irrational Numbers}} are {{c2::all the numbers that aren't rational}}

*** Real Numbers
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525429541
:END:

**** Text

math: {{c1::Real Numbers}} are numbers that are {{c2::either rational or irrational}}

*** Natural Numbers Symbol
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525429709
:END:

**** Text

math: {{c1::Natural Numbers Symbol}} = {{c2::ℕ}}

*** Integers Symbol
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525430097
:END:

**** Text

math: {{c1::Integers Symbol}} = {{c2::ℤ}}

*** Rational Numbers Symbol
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525430340
:END:

**** Text

math: {{c1::Rational Numbers Symbol}} = {{c2::ℚ}}

*** Real Numbers Symbol
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525430543
:END:

**** Text

math: {{c1::Real Numbers Symbol}} = {{c2::ℝ}}

*** R includes Q which includes Z which includes N
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525430716
:END:

**** Text

math: {{c1::Real}} Numbers include {{c1::Rational Numbers}} wich include {{c1::Integers}} which include
{{c1::Natural Numbers}}

** 7.3 Distributive Property
*** Left Distributive Property

f is left-distributive over g if f(a, g(b, c)) = g(f(a, b), f(a, c))

*** Right Distributive Property

f is right-distributive over g if f(g(b, c), a) = g(f(b, a), f(c, a))

** 7.4 Properties of Identity, Inverses, and Zero
*** Identity Element
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525430935
:END:

**** Text

math: x is the {{c1::identity element}} of f if {{c2::f(x, y) = y}}

** 9.3 Use Properties of Angles, Triangles, and the Pythagorean Theorem
*** Supplementary Angles
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525431118
:END:

**** Text

math: Two angles are {{c1::Supplementary}} if {{c2::their sum is 180°}}

*** Complementary Angles
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525431387
:END:

**** Text

math: Two angles are {{c1::Complementary}} if {{c2::their sum is 90°}}

*** Similar Figures
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525431529
:END:

**** Text

math: Two figures are {{c1::Similar}} if {{c2::they have the same shape}}

*** Similar Triangles Angles
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525431656
:END:

**** Text

math: Two Similar Triangles {{c1::have the same}} angles

*** Congruent Figures
:PROPERTIES:
:Source: https://en.wikipedia.org/wiki/Congruence_(geometry)
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525432299
:END:

**** Text

math: Two figures are {{c1::Congruent}} if {{c2::they have the same shape and size}}

** 9.4 Use Properties of Rectangles, Triangles, and Trapezoids
*** Triangle Area
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525432460
:END:

**** Text

math: Triangle Area = {{c1::1/2 * (base * height)}}

*** Sum of Triangle Angles
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525432622
:END:

**** Text

math: The sum of a triangle angles = {{c1::180°}}

*** Trapezoid
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525432765
:END:

**** Text

math: A {{c1::Trapezoid}} is {{c2::a quadrilateral with at least one pair of parallel sides}}

*** Trapezoid Area
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525432896
:END:

**** Text

math: Trapezoid Area = {{c1::1/2 * height * (big base + small base)}}

*** Trapezoid Area
:PROPERTIES:
:Source: https://math.stackexchange.com/a/277033
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525433065
:END:

**** Text

math: The Area of a Trapezoid can be thought of as {{c1::the area of two triangles}}

** 9.5 Solve Geometry Applications: Circles and Irregular Figures
*** Circle Circumference
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525433193
:END:

**** Text

math: Circle Circumference = {{c1::2πr}}

*** Circle Area
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525433395
:END:

**** Text

math: Circle Area = {{c1::πr^2}}

** 9.6 Solve Geometry Applications: Volume and Surface Area
*** Sphere Surface Area
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525433556
:END:

**** Text

math: Sphere Surface Area = {{c1::4πr^2}}

*** Sphere Volume
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525434314
:END:

**** Text

math: Sphere Volume = {{c1::4/3 * πr^3}}

*** Circle Circumference and Area and Sphere Surface and Volume
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525434506
:END:

**** Text

math:
- Circle Circumference = {{c1::$2 \pi r$}}
- Circle Area = {{c1::$\pi r^2$}}
- Sphere Surface = {{c1::$4 \pi r^2$}}
- Sphere Volume = {{c1::$\frac{4}{3} \pi r^3$}}

*** Cylinder Surface Area
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525434612
:END:

**** Text

math: Cylinder Surface Area = {{c1::2 * surface of base + surface of rectangle = 2πr^2 + 2πr * height}}

*** Cylinder Volume
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525434787
:END:

**** Text

math: Cylinder Volume = {{c1::surface of base * height = πr^2 * height}}

*** Cone Volume
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525434977
:END:

**** Text

math: Cone Volume = {{c1::1/3 * surface of base * height = 1/3 * πr^2 * height}}

** 10.1 Add and Subtract Polynomials
*** Degree of a Polynomial
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525435151
:END:

**** Text

math: The degree of a Polynomial is the {{c1::highest degree of all its terms}}

*** Polynomial Terms Order
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525435321
:END:

**** Text

math: The Standard Form of a Polynomial lists the terms {{c1::in decreasing order of degrees}}

** 10.2 Use Multiplication Properties of Exponents
*** Product Property of Exponents
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525435489
:END:

**** Text

math: {{c1::a^m * a^n}} = {{c2::a^(m + n)}}

*** Power Property of Exponents
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525436094
:END:

**** Text

math: {{c1::(a^m)^n}} = {{c2::a^(mn)}}

*** Product to a Power Property of Exponents
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525436249
:END:

**** Text

math: {{c1::(ab)^m}} = {{c2::a^m * b^m}}

** 10.4 Divide Monomials
*** Quotient Property of Exponents
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525436414
:END:

**** Text

math: {{c1::a^m / a^n}} = {{c2::a^(m - n)}}

*** Quotient to a Power Property of Exponents
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525436554
:END:

**** Text

math: {{c1::(a / b)^m}} = {{c2::a^m / b^m}}

** 10.5 Integer Exponents and Scientific Notation
*** Negative Exponent
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525436727
:END:

**** Text

math: {{c1::a^-n}} = {{c2::1 / a^n}}

** 11.3 Graphing with Intercepts
*** Intercepts of a Line
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525436930
:END:

**** Text

math: {{c1::An Intercept of a Line}} is {{c2::a point where the line crosses the x or y-axis}}

*** x-intercept of a Line
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525437103
:END:

**** Text

math: An *x-intercept* is a point where a line crosses the {{c1::x-axis}}

*** y-intercept of a Line
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525437241
:END:

**** Text

math: A *y-intercept* is a point where a line crosses the {{c1::y-axis}}

** 11.4 Understand Slope of a Line
*** Formula of the Slope of a Line
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525437385
:END:

**** Text

math: Formula of the Slope of a Line = {{c1::Rise/Run}} or {{c1::(y2 - y1)/(x2 - x1)}} or
{{c1::m in y = mx + b}}

* Openstax - Elementary Algebra 2e
:LOGBOOK:
CLOCK: [2020-11-22 Sun 11:03]--[2020-11-22 Sun 14:03] =>  3:00
CLOCK: [2020-11-16 Mon 14:50]--[2020-11-16 Mon 17:50] =>  3:00
CLOCK: [2020-11-10 Tue 11:09]--[2020-11-10 Tue 15:09] =>  4:00
CLOCK: [2020-11-05 Thu 10:22]--[2020-11-05 Thu 14:22] =>  4:00
CLOCK: [2020-11-03 Tue 11:16]--[2020-11-03 Tue 13:16] =>  2:00
CLOCK: [2020-10-31 Sat 10:39]--[2020-10-31 Sat 13:39] =>  3:00
CLOCK: [2020-10-29 Thu 12:08]--[2020-10-29 Thu 16:08] =>  4:00
CLOCK: [2020-10-23 Fri 13:56]--[2020-10-23 Fri 17:56] =>  4:00
CLOCK: [2020-10-19 Mon 08:01]--[2020-10-19 Mon 11:01] =>  3:00
CLOCK: [2020-10-15 Thu 16:03]--[2020-10-15 Thu 18:03] =>  2:00
CLOCK: [2020-10-13 Tue 14:24]--[2020-10-13 Tue 18:24] =>  4:00
CLOCK: [2020-10-07 Wed 13:41]--[2020-10-07 Wed 16:41] =>  3:00
CLOCK: [2020-10-05 Mon 10:30]--[2020-10-05 Mon 14:30] =>  4:00
CLOCK: [2020-10-01 Thu 14:39]--[2020-10-01 Thu 17:39] =>  3:00
CLOCK: [2020-09-30 Wed 16:29]--[2020-09-30 Wed 19:29] =>  3:00
CLOCK: [2020-09-29 Tue 15:43]--[2020-09-29 Tue 18:43] =>  3:00
CLOCK: [2020-09-28 Mon 11:13]--[2020-09-28 Mon 14:13] =>  3:00
CLOCK: [2020-09-27 Sun 13:33]--[2020-09-27 Sun 16:33] =>  3:00
CLOCK: [2020-09-24 Thu 14:29]--[2020-09-24 Thu 17:29] =>  3:00
CLOCK: [2020-09-23 Wed 10:48]--[2020-09-23 Wed 13:48] =>  3:00
CLOCK: [2020-09-21 Mon 14:59]--[2020-09-21 Mon 16:59] =>  2:00
CLOCK: [2020-09-19 Sat 13:58]--[2020-09-19 Sat 17:58] =>  4:00
CLOCK: [2020-09-17 Thu 11:28]--[2020-09-17 Thu 15:28] =>  4:00
CLOCK: [2020-09-16 Wed 13:23]--[2020-09-16 Wed 17:23] =>  4:00
CLOCK: [2020-09-14 Mon 15:40]--[2020-09-14 Mon 17:40] =>  2:00
CLOCK: [2020-09-14 Mon 09:12]--[2020-09-14 Mon 11:12] =>  2:00
CLOCK: [2020-09-13 Sun 11:49]--[2020-09-13 Sun 14:49] =>  3:00
CLOCK: [2020-08-20 Thu 13:33]--[2020-08-20 Thu 14:33] =>  1:00
CLOCK: [2020-08-19 Wed 10:18]--[2020-08-19 Wed 11:18] =>  1:00
CLOCK: [2020-08-15 Sat 11:52]--[2020-08-15 Sat 14:52] =>  3:00
:END:

** 1.6 Add and Subtract Fractions
*** Find the Least Common Multiple Using the Prime Factorization
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525438039
:END:

**** Text

math: Using the *Prime Factorization*, the *Least Common Multiple* of two numbers is
{{c1::the multiplication of their prime factors to their highest powers}}
Example lcm(8, 18, 21) = {{c1::2^3 * 3^2 * 7^1}}

** 2.4 Use a General Strategy to Solve Linear Equations
*** Conditional Equation
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525438233
:END:

**** Text

math: {{c1::An equation that is true for some values of the variable (eg. 2 x = 4)}} is a
{{c2::Conditional Equation}}

*** Identity Equation
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525438434
:END:

**** Text

math: {{c1::An equation that is true for any value of the variable (eg. x + 3 = x + 3)}} is
{{c2::an Identity Equation}}

*** Contradiction Equation
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525438909
:END:

**** Text

math: {{c1::An equation that is false for all values of the variable (eg. x = x + 1)}} is
{{c2::a Contradiction Equation}}

** 2.5 Solve Equations with Fractions or Decimals
*** Solve Equations with Fractions
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525439030
:END:

**** Text

math: To easily simplify equations with fractions {{c1::multiply both sides of the equation by the LCD
of all the fractions (you need to multiply by a number that is divisible by all the denominators)}}

** 2.7 Solve Linear Inequalities
*** Interval Notation
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525439168
:END:

**** Text

math: An {{c1::Interval Notation}} is written as {{c2::[X, Y] when X and Y are included or (X, Y)
otherwise}}

*** Dividing or Multiplying an Inequality by a Negative Number
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525439313
:END:

**** Text

math: When you divide or multiply an inequality by a negative number,
the inequality {{c1::reverses}}

*** Dividing or Multiplying an Inequality by a Positive Number
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525439462
:END:

**** Text

math: When you divide or multiply an inequality by a positive number,
the inequality {{c1::stays the same}}

*** Solve an Inequality
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525439621
:END:

**** Text

math: Solve -10x >= 50 and give the solution as an interval notation
{{c1::
#+BEGIN_SRC
-10x >= 50
x =< -5
Solution: (-∞, -5]
#+END_SRC
}}

** 3.6 Solve Applications with Linear Inequalities
*** Linear Inequality Application
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525439787
:END:

**** Text

math: Translate the following to an Inequality:
Bob plans to rent a car from a company that charges $75 a week plus $0.25 a mile. How many miles can
he travel and still keep within his $200 budget?
{{c1::
75 + 0.25m <= 200
}}

** 4.5 Use the Slope-Intercept Form of an Equation of a Line
*** Parallel Lines
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525439945
:END:

**** Text

math: {{c1::Parallel}} lines have {{c2::the same}} slope

*** Perpendicular Lines
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525440177
:END:

**** Text

math: {{c1::Perpendicular}} lines have {{c2::slopes that are the negative reciprocals of each other::slope}}

** 4.7 Graphs of Linear Inequalities
*** Dashed Boundary Line
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525440581
:END:

**** Text

math: inequality graph: A {{c1::Dashed}} Boundary Line means the line {{c2::isn't}} included in the solution

*** Solid Boundary Line
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525440757
:END:

**** Text

math: inequality graph: A {{c1::Solid}} Boundary Line means the line {{c2::is}} included in the solution

** 5.1 Solve Systems of Equations by Graphing
*** Coincident Lines
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525440877
:END:

**** Text

math: {{c1::Coincident Lines}} have {{c2::the same slope and y-intercept}}

*** Consistent System
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525441020
:END:

**** Text

math: {{c1::A Consistent}} System of Equations has {{c2::at least one}} solution

*** Inconsistent System
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525441185
:END:

**** Text

math: {{c1::An Inconsistent}} System of Equations has {{c2::no solution}}

*** Dependent Equations
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525441330
:END:

**** Text

math: {{c1::Dependent}} Equations have {{c2::the same}} solutions

*** Independent Equations
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525441540
:END:

**** Text

math: {{c1::Independent}} Equations have {{c2::different}} solutions

** 5.2 Solving Systems of Equations by Substitution
*** Solve a System of Equations by Substitution
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525441677
:END:

**** Text

#+BEGIN_SRC
math: Solve the following system by Substitution:
x + 2y = 4
x + 3y = 2

{{c1::
x = 4 - 2y (isolate x in the first equation)

4 - 2y + 3y = 2 (substitute x in the second equation)
y = -2

x + 2(-2) = 4 (use y in one of the equations (here the first))
x = 8

8 + 2(-2) = 4 (check that the solution is correct in the first equation)
4 = 4

8 + 3(-2) = 2 (check that the solution is correct in the second equation)
2 = 2

Solution: (8, -2)
}}
#+END_SRC

** 5.3 Solve Systems of Equations by Elimination
*** Based on Addition Property of Equality
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525441815
:END:

**** Text

math: Solving Systems of Equations by Elimination is based on the {{c1::addition/substraction property
of equality}}

*** Solve a System of Equations by Elimination
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525442266
:END:

**** Text

#+BEGIN_SRC
math: Solve the following system by Elimination:
x + 3y = 2
x + 2y = 4

{{c1::
x + 3y - x - 2y = 2 - 4 (substract the second equation from the first one)
y = -2

x + 2(-2) = 4 (use y in one of the equations)
x = 8

8 + 3(-2) = 2 (check that the solution is correct in the first equation)
2 = 2

8 + 2(-2) = 4 (check that the solution is correct in the second equation)
4 = 4

Solution: (8, -2)
}}
#+END_SRC

** 6.1 Add and Subtract Polynomials
*** Degree of a Polynomial Term
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525442624
:END:

**** Text

math: The degree of a Polynomial Term is {{c1::the sum of the exponents of its variables}}

** 6.4 Special Products
*** Squared Binomial
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525442857
:END:

**** Text

math: pattern: {{c1::(a + b)^2}} = {{c2::a^2 + 2ab + b^2}}

*** Squared Binomial
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525442995
:END:

**** Text

math: pattern: {{c1::(a - b)^2}} = {{c2::a^2 - 2ab + b^2}}

*** Conjugate Pair
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525443140
:END:

**** Text

math: A {{c1::Conjugate Pair}} is {{c2::two binomials of the form (a + b),(a - b)::form}}

*** Multiplied Conjugate Pair
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525443297
:END:

**** Text

math: pattern: {{c1::(a + b)(a - b)}} = {{c2::a^2 - b^2}}

** 6.6 Divide Polynomials
*** Divide a Polynomial by a Binomial
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525443446
:END:

**** Text

math: Divide (2x^2 + 4) by (x - 2):
{{c1::
#+BEGIN_SRC
        2x + 4 + 12/(x - 2)
       ____________________
x - 2 | 2x^2 + 0x + 4
      -(2x^2 - 4x)
               4x + 4
             -(4x - 8)
                   12
#+END_SRC
}}

** 6.7 Integer Exponents and Scientific Notation
*** Negative Exponent
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525443594
:END:

**** Text

math: {{c1::a^-n}} = {{c2::1/a^n}}

*** Negative Exponent
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525444049
:END:

**** Text

math: 1/a^-n = {{c1::a^n}}

*** Quotient to a Negative Exponent Property
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525444231
:END:

**** Text

math: {{c1::(a/b)^-n}} = {{c2::(b/a)^n}}

** 7.1 Greatest Common Factor and Factor by Grouping
*** Factor out the GCF
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525444431
:END:

**** Text

math: Factor 4y^2 + 24y + 28
{{c1::
#+BEGIN_SRC
Factor out the GCF:
4y^2 + 24y + 28 = 4(y^2 + 6y + 7)
#+END_SRC
}}

*** Factor by Grouping
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525444699
:END:

**** Text

math: Factor xy + 3y + 2x + 6
{{c1::
#+BEGIN_SRC
Factor by grouping:
xy + 3y + 2x + 6 = y(x + 3) + 2(x + 3)
                 = (y + 2)(x + 3)
#+END_SRC
}}

** 7.2 Factor Trinomials of the Form x2+bx+c
*** Factor Trinomials of the Form x^2 + bx + c
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525444917
:END:

**** Text

math: Factor x^2 - 11x + 24
{{c1::
#+BEGIN_SRC
x^2 + bx + c = (x + m)(x + n) with b = m + n and c = m * n
b = -11 = -3 + -8
c =  24 = -3 * -8
So x^2 - 11x + 24 = (x - 3)(x - 8)
#+END_SRC
}}

*** Factor Trinomials of the Form x^2 + bx + c
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525445090
:END:

**** Text

math: Factor x^2 + 4x - 5
{{c1::
#+BEGIN_SRC
x^2 + bx + c = (x + m)(x + n) with b = m + n and c = m * n
b =  4 = 5 + -1
c = -5 = 5 * -1
So x^2 + 4x - 5 = (x + 5)(x - 1)
#+END_SRC
}}

*** Prime Polynomial
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525445254
:END:

**** Text

math: {{c1::A Prime Polynomial}} is {{c2::a Polynomial that cannot be factorized}}

*** Prime Polynomial aka Irreducible Polynomial
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525445401
:END:

**** Text

math: {{c1::Prime Polynomial}} aka {{c2::Irreducible Polynomial}}

*** Factor Prime Trinomial
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525445559
:END:

**** Text

math: Factor y^2 − 6y + 15
{{c1::
#+BEGIN_SRC
y^2 − 6y + 15 is irreducible over the integers
#+END_SRC
}}

*** Factor Trinomials of the Form x^2 + bxy + cy^2
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525446000
:END:

**** Text

math: Factor x^2 - 8xy + 15y^2
{{c1::
#+BEGIN_SRC
x^2 - 8xy + 15y^2 = (x + m)(x + n) with b = m + n and c = m * n
b = 8y    = -5y - 3y
c = 15y^2 = -5y * -3y
So x^2 - 8xy + 15y^2 = (x - 5y)(x - 3y)
#+END_SRC
}}

** 7.3 Factor Trinomials of the Form ax2+bx+c
*** Factor Using the AC Method
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525446266
:END:

**** Text

math: Factor 6x^2 + 7x + 2
{{c1::
#+BEGIN_SRC
Factor with the ac method:
6x^2 + 7x + 2 = ax^2 + mx + nx + c with b = m + n and  a * c = m * n
ac = 12
b = 7
Possible factors of 12 are:
12 * 1 > 12 + 1 = 13
6 * 2  > 6 + 2  = 8
4 * 3  > 4 + 3  = 7 = b
So 6x^2 + 7x + 2 = 6x^2 + 4x + 3x + 2
Factor by grouping:
6x^2 + 4x + 3x + 2 = 3x(2x + 1) + 2(2x + 1) = (3x + 2)(2x + 1)
#+END_SRC
}}

** 7.4 Factor Special Products
*** Sum of Cubes Pattern
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525446475
:END:

**** Text

math: pattern: {{c1::a^3 + b^3}} = {{c2::(a + b)(a^2 - ab + b^2)}}

*** Difference of Cubes Pattern
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525446646
:END:

**** Text

math: pattern: {{c1::a^3 - b^3}} = {{c2::(a - b)(a^2 + ab + b^2)}}

*** Factor a^2 + 2ab + b^2
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525446858
:END:

**** Text

math: Factor 4n^2 + 12n + 9
{{c1::
#+BEGIN_SRC
4n^2 + 12n + 9 is of the form a^2 + 2ab + b^2 = (a + b)^2
4n^2 + 12n + 9 = (2n + 3)^2
#+END_SRC
}}

*** Factor a^2 - 2ab + b^2
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525447026
:END:

**** Text

math: Factor 100x^2 − 20x + 1
{{c1::
#+BEGIN_SRC
100x^2 − 20x + 1 is of the form a^2 - 2ab + b^2 = (a - b)^2
100x^2 − 20x + 1 = (10x - 1)^2
#+END_SRC
}}

*** Factor a^2 - b^2
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525447190
:END:

**** Text

math: Factor 27q^2 - 3
{{c1::
#+BEGIN_SRC
27q^2 - 3 = 3(9q^2 - 1)
9q^2 - 1 is of the form a^2 - b^2 = (a + b)(a - b)
3(9q^2 - 1) = 3(3q + 1)(3q - 1)
#+END_SRC
}}

*** Factor a^3 + b^3
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525447338
:END:

**** Text

math: Factor x^3 + 64
{{c1::
#+BEGIN_SRC
x^3 + 64 is of the form a^3 + b^3 = (a + b)(a^2 - ab + b^2)
x^3 + 64 = (x + 4)(x^2 - 4x + 16)
#+END_SRC
}}

*** Factor a^3 - b^3
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525447805
:END:

**** Text

math: Factor 27 - 125p^3
{{c1::
#+BEGIN_SRC
27 - 125p^3 is of the form a^3 - b^3 = (a - b)(a^2 + ab + b^2)
27 - 125p^3 = (3 - 5p)(9 + 15p + 25p^2)
#+END_SRC
}}

*** Factor a^4 - b^4
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525447939
:END:

**** Text

math: Factor m^4 - n^4
{{c1::
#+BEGIN_SRC
m^4 - n^4 is of the form a^2 - b^2 = (a + b)(a - b)
m^4 - n^4 = (m^2 + n^2)(m^2 - n^2)
m^2 - n^2 is of the form a^2 - b^2 = (a + b)(a - b)
(m^2 + n^2)(m^2 - n^2) = (m^2 + n^2)(m + n)(m - n)
#+END_SRC
}}

*** Factor an Irreducible Polynomial
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525448084
:END:

**** Text

math: Factor 9x^2 + 4
{{c1::
#+BEGIN_SRC
9x^2 + 4 is irreducible over the integers
#+END_SRC
}}

** 7.5 General Strategy for Factoring Polynomials
*** General Strategy for Factoring Polynomials
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525448223
:END:

**** Text

math: General Strategy for Factoring Polynomials
{{c1::
#+BEGIN_SRC
- Factor out the GCF if there is one
- For binomials:
  - If of the form a^2 + b^2: Do nothing
  - If of the form a^2 - b^2: (a + b)(a - b)
  - If of the form a^3 + b^3: (a + b)(a^2 - ab + b^2)
  - If of the form a^3 - b^3: (a - b)(a^2 + ab + b^2)
- For trinomials:
  - If of the form x^2 + bx + c: (x + m)(x + n) where b = m + n and c = m * n
  - If of the form ax^2 + bx + c:
    - If a and c are perfect squares:
      - If of the form a^2 + 2ab + b^2: (a + b)^2
      - If of the form a^2 - 2ab + b^2: (a - b)^2
    - The ac method: ax^2 + mx + nx + c with b = m + n and  a * c = m * n, then use grouping
    - Or use the trial and error method
- If it has more than 3 terms: Use grouping
#+END_SRC
}}

** 7.6 Quadratic Equations
*** Quadratic Equation
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525448409
:END:

**** Text

math: A {{c1::Quadratic Equation}} is an equation of the form {{c2::ax^2 + bx + c = 0}}

*** Solve a Quadratic Equation by Factoring
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525448611
:END:

**** Text

math: Solve a Quadratic Equation by Factoring by:
- {{c1::Writing it in standard form}}
- {{c1::Factoring it completely}}
- {{c1::Using the Zero Product property}}
- {{c1::Solving the linear equations}}

*** Example of Solving a Quadratic Equation
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525448889
:END:

**** Text

math: Solve 3c^2 = 10c − 8 by factoring
{{c1::
#+BEGIN_SRC
Write in standard form:
3c^2 - 10c + 8 = 0

Factor (with the ac method):
ac = 24 = 6 * 4
b = 10 = 6 + 4

3c^2 - 6c - 4c + 8 = 0
3c(c - 2) - 4(c - 2) = 0
(3c - 4)(c - 2) = 0

Use the Zero Product property:
If (3c - 4)(c - 2) = 0 then either 3c - 4 = 0 or c - 2 = 0 or both.

Solve the linear equations:
3c - 4 = 0
3c = 4
c = 4/3

c - 2 = 0
c = 2

Solutions:
c = 4/3 or c = 2
#+END_SRC
}}

** 8.1 Simplify Rational Expressions
*** Rational Expression
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525449106
:END:

**** Text

math: A {{c1::Rational Expression}} is {{c2::an expression of the form f(x)/g(x) where f and g are polynomials}}

*** Rational Fraction
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525449533
:END:

**** Text

math: {{c1::Rational Expression}} aka {{c2::Rational Fraction}}

*** Opposites in a Rational Expression
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525449691
:END:

**** Text

math: (a - b)/(b - a) = {{c1::(a - b)/-(a - b)}} = {{c1::-1}}

** 8.4 Add and Subtract Rational Expressions with Unlike Denominators
*** Find the Least Common Multiple of Polynomials
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525449839
:END:

**** Text

math: Find the Least Common Multiple of polynomials by {{c1::factoring them completely and multiplying
their factors to their highest powers}}
Example: lcm(a^2 - b^2, (a + b)^2) = {{c1::(a - b)(a + b)^2}}

*** Add and Subtract Rational Expressions with Unlike Denominators
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525449972
:END:

**** Text

math: To add rational expressions with unlike denominators:
- {{c1::Find the Least Common Denominator}}
- {{c1::Multiply the fractions' denominator and numerator by the factors their denominator was missing}}
- {{c1::Add the rational expressions now that they have the same denominators}}

*** Example Add and Subtract Rational Expressions with Unlike Denominators
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525450133
:END:

**** Text

math: Simplify $\frac{4}{cd + 3c} + \frac{1}{d^2 - 9}$
{{c1::
\begin{gather*}
\text{Factor the denominators} \\
cd + 3c = c(d + 3) \\
d^2 - 9 = (d + 3)(d - 3) \\
\\
\text{Find the least common denominator} \\
lcm(cd + 3c, d^2 - 9) = c(d + 3)(d - 3) \\
\\
\text{Multiply the numerators and denominators by} \\
\text{the factors the denominators were missing} \\
\frac{4(d - 3)}{c(d + 3)(d - 3)} + \frac{c}{c(d + 3)(d - 3)} \\
\\
\text{Add} \\
\frac{4(d - 3) + c}{c(d + 3)(d - 3)} \\
\end{gather*}
}}

** 8.5 Simplify Complex Rational Expressions
*** Complex Rational Expression
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525450276
:END:

**** Text

math: A {{c1::Complex Rational Expression}} is a {{c2::rational expression whose numerator or denominator
contains a rational expression}}

*** Simplify Complex Rational Expressions
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525450421
:END:

**** Text

math: Simplify a Complex Rational Expression by either:
- {{c1::Multiplying the numerator by the reciprocal of the denominator}}
- {{c1::Multiplying the numerator and denominator by the LCD of all the fractions}}
Example:
{{c1::
\begin{gather*}
\text{Multiplying the numerator by the reciprocal of the denominator} \\
\frac{ \frac{a}{b} }
     { \frac{x}{y} } \\
\frac{a}{b} \cdot \frac{y}{x} \\
\frac{ay}{bx} \\
\text{Multiplying the numerator and denominator by the LCD of all the fractions} \\
\frac{ \frac{a}{b} }
     { \frac{x}{y} } \\
\frac{\frac{a}{b} \cdot by}
     {\frac{x}{y} \cdot by} \\
\frac{ay}{bx}
\end{gather*}
}}

*** Example of Simplifying Complex Rational Expressions by Multiplying by the Reciprocal
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525450604
:END:

**** Text

math: Simplify $\frac{\frac{1}{x} + \frac{1}{y}}{\frac{x}{y} - \frac{y}{x}}$ using the reciprocal
method
{{c1::
\begin{gather*}
\text{Simplify the numerator and denominator} \\
\frac{ \frac{y + x}{xy} }
     { \frac{x^2 - y^2}{xy} } \\
\text{Multiply the numerator by the reciprocal of the denominator} \\
\frac{(y + x)xy}{xy(x^2 - y^2)} \\
\text{Simplify} \\
\frac{1}{x - y}
\end{gather*}
}}

*** Example of Simplifying Complex Rational Expressions by Multiplying by the LCD
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525451056
:END:

**** Text

math: Simplify $\frac{\frac{1}{x} + \frac{1}{y}}{\frac{x}{y} - \frac{y}{x}}$ using the LCD method
{{c1::
\begin{gather*}
\text{Mutiply the numerator and denominator by the LCD ($xy$):} \\
\frac{ \color{red}{xy} \cdot \frac{1}{x} + \color{red}{xy} \cdot \frac{1}{y} }
     { \color{red}{xy} \cdot \frac{x}{y} - \color{red}{xy} \cdot \frac{y}{x} } \\
\text{Simplify} \\
\frac{y + x}{x^2 - y^2} \\
\frac{1}{x - y}
\end{gather*}
}}

** 8.6 Solve Rational Equations
*** Extraneous Solution
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525451219
:END:

**** Text

math: {{c1::An Extraneous Solution}} to an equation is {{c2::a solution that would make the equation be
undefined}}

** 8.7 Solve Proportion and Similar Figure Applications
*** Proportion
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525451416
:END:

**** Text

math: A {{c1::Proportion}} is an equation of the form {{c2::a/b = c/d}}

*** Proportion Reading
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525451647
:END:

**** Text

math: A proportion a/b = c/d is read as {{c1::a is to b as c is to d}}

*** Proportion Work Application
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525451812
:END:

**** Text

math: Bob can paint a room in 6 hours. Alice takes 12 hours to paint the same room. How long would
it take Bob and Alice to paint the room if they worked together?
{{c1::
#+BEGIN_SRC
Translate to an equation:
1/6 + 1/12 = 1/x

Multiply by the LCD of all the fractions to remove them:
12x(1/6 + 1/12) = 12x*1/x
2x + x = 12

Simplify:
3x = 12
x = 12/3
x = 4

Answer: 4 hours
#+END_SRC
}}

** 8.9 Use Direct and Inverse Variation
*** Direct Variation
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525452025
:END:

**** Text

math: x varies directly with y if {{c1::x = ky}}

*** Direct Variation Example
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525452178
:END:

**** Text

math: The distance a moving body travels, d, varies directly with the time, t, it moves. A train
travels 100 miles in 2 hours.
Write the equation that relates d and t.
{{c1::
#+BEGIN_SRC
d = kt
100 = k2
k = 50

Answer: d = 50t
#+END_SRC
}}

How many miles would it travel in 5 hours?
{{c1::
#+BEGIN_SRC
miles = kt = 50 * 5 = 250 miles
#+END_SRC
}}

*** Inverse Variation
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525452327
:END:

**** Text

math: x varies inversely with y if {{c1::x = k/y}}

*** Inverse Variation Example
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525452477
:END:

**** Text

math: The time required to empty a tank varies inversely with the rate of pumping. It took Janet 5
hours to pump her flooded basement using a pump that was rated at 200 gpm (gallons per minute).
Write the equation that relates the number of hours to the pump rate.
{{c1::
#+BEGIN_SRC
time = k/rate
5 = k/200
k = 5 * rate = 1000

Answer: time = 1000/rate
#+END_SRC
}}

How long would it take Janet to pump her basement if she used a pump rated at 400 gpm?
{{c1::
#+BEGIN_SRC
time = 1000/rate = 1000/400 = 2.5
#+END_SRC
}}

** 9.2 Simplify Square Roots
*** Product Property of Square Roots
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525452904
:END:

**** Text

math: {{c1::$\sqrt{ab}$}} = {{c2::$\sqrt{a}\sqrt{b}$}}

*** Quotient Property of Square Roots
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525453063
:END:

**** Text

math: {{c1::$\sqrt{ \frac{a}{b} }$}} = {{c2::$\frac{ \sqrt{a} }{ \sqrt{b} }$}}

** 9.5 Divide Square Roots
*** Simplify a Fraction with a Monomial
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525453173
:END:

**** Text

math: Simplify and rationalize $\sqrt{\frac{11}{28}}$
{{c1::
\begin{gather*}
\sqrt{ \frac{11}{28} } \\
\frac{ \sqrt{11} }{ 2\sqrt{7} } \\
\frac{ \sqrt{11} \cdot \color{red}{ \sqrt{7} } }{ 2\sqrt{7} \cdot \color{red}{ \sqrt{7} } } \\
\frac{ \sqrt{77} }{2 \cdot 7} \\
\frac{ \sqrt{77} }{14}
\end{gather*}
}}

*** Simplify a Fraction with a Binomial
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525453308
:END:

**** Text

math: Simplify $\frac{4}{4 + \sqrt{2}}$
{{c1::
\begin{gather*}
\frac{4}{ 4 + \sqrt{2} } \\
\frac{ 4\color{red}{(4 - \sqrt{2})} }{ (4 + \sqrt{2}) \color{red}{(4 - \sqrt{2})} } \\
\frac{4(4 - \sqrt{2})}{16 - 2} \\
\frac{4(4 - \sqrt{2})}{14} \\
\frac{2(4 - \sqrt{2})}{7}
\end{gather*}
}}

** 9.6 Solve Equations with Square Roots
*** Solve a Radical Equation with a Monomial
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525453482
:END:

**** Text

math: Solve $\sqrt{5n - 4} - 9 = 0$
{{c1::
\begin{gather*}
\sqrt{5n - 4} = 9 \\
5n - 4 = 81 \\
5n = 85 \\
n = 17
\end{gather*}
}}

*** Solve a Radical Equation with a Binomial
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525453642
:END:

**** Text

math: Solve $\sqrt{p - 1} + 1 = p$
{{c1::
\begin{gather*}
\sqrt{p - 1} = p - 1 \\
p - 1 = (p - 1)^2 \\
p - 1 = p^2 - 2p + 1 \\
0 = p^2 - 3p + 2 \\
0 = (p - 2)(p - 1) \\
p = 2 \text{ or } p = 1 \\
\\
\text{Check for extraneous solutions:} \\
\sqrt{2 - 1} + 1 = 2 \\
1 + 1 = 2 \text{, OK} \\
\\
\sqrt{1 - 1} + 1 = 1 \\
0 + 1 = 1 \text{, OK} \\
\\
\text{Solution: p = 2 or p = 1}
\end{gather*}
}}

*** Solve a Radical Equation with no Real Solution
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525453850
:END:

**** Text

math: Solve $\sqrt{9k - 2} + 1 = 0$
{{c1::
\begin{gather*}
\sqrt{9k - 2} = -1 \\
\text{Since the square root is a negative number, there is no real solution.}
\end{gather*}
}}

*** Solve a Radical Equation with an Extraneous Solution
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525454143
:END:

**** Text

math: Solve $\sqrt{r + 4} - r + 2 = 0$
{{c1::
\begin{gather*}
\sqrt{r + 4} = r - 2 \\
r + 4 = r^2 - 4r + 4 \\
0 = r^2 - 5r \\
0 = r(r - 5) \\
r = 0 \text{ or } r = 5 \\
\\
\text{Check for extraneous solutions:} \\
\sqrt{0 + 4} - 0 + 2 = 0 \\
2 + 2 = 0 \\
4 \neq 0 \text{, 0 is an extraneous solution} \\
\\
\sqrt{5 + 4} - 5 + 2 = 0 \\
3 - 5 + 2 = 0 \\
0 = 0 \text{, OK} \\
\\
\text{Solution: r = 5}
\end{gather*}
}}

** 9.7 Higher Roots
*** nth Root
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525454581
:END:

**** Text

math: If {{c1::a^n = b}} then a is {{c2::an nth root of b}}

*** nth Root Index
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525454747
:END:

**** Text

math: In $\sqrt[n]{x}$ n is called {{c1::the Index}}

*** Real or Imaginary Roots
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525454900
:END:

**** Text

math: State the type of the root of $\sqrt[n]{x}$ depending on n and x:
{{c1::
#+BEGIN_SRC
- If n is even
  - and x >= 0 then the root is a real number
  - and x < 0 then the root is an imaginary number
- If n is odd
  - The root is always a real number
#+END_SRC
}}

*** Root with an Even Index
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525455029
:END:

**** Text

math: $\sqrt[4]{x^{12}}$ = {{c1::$|x^3|$}}

*** Root with an Even Index
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525455140
:END:

**** Text

math: $\sqrt[4]{48y^6}$ = {{c1::$2|y|\sqrt[4]{3y^2}$}}

*** Root of a Negative Number
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525455285
:END:

**** Text

math: $\sqrt[6]{-64}$ = {{c1::Not a Real Number}}

** 9.8 Rational Exponents
*** Root is the Same as a Rational Exponent
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525455441
:END:

**** Text

math: {{c1::$\sqrt[n]{a}$}} (root form) = {{c2::$a^\frac{1}{n}$}} (exponent form)

*** Negative Rational Exponent
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525455600
:END:

**** Text

math: Simplify $16^{-\frac{3}{2}}$
{{c1::
\begin{gather*}
\frac{1}{ 16^\frac{3}{2} } \\
\frac{1}{64}
\end{gather*}
}}

** 10.1 Solve Quadratic Equations Using the Square Root Property
*** Solve a Quadratic Equation of the Form ax^2 = k Using the Square Root Property
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525455835
:END:

**** Text

math: Solve $x^2 - 48 = 0$
{{c1::
\begin{align*}
x^2 &= 48 \\
x &= \pm \sqrt{48} \\
x &= \pm 4 \sqrt{3}
\end{align*}
}}

*** Solve a Quadratic Equation of the Form ax^2 = k Where k < 0
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525456484
:END:

**** Text

math: Solve $x^2 + 24 = 0$
{{c1::
\begin{gather*}
x^2 = -24 \\
x = \pm \sqrt{-24} \\
\text{There is no real solution}
\end{gather*}
}}

*** Solve a Quadratic Equation of the Form a(x − h)^2 = k
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525456623
:END:

**** Text

math: Solve $(x - 2)^2 + 3 = 30$
{{c1::
\begin{gather*}
(x - 2)^2 = 27 \\
x - 2 = \pm \sqrt{27} \\
x - 2 = \pm 3 \sqrt{3} \\
x = 2 \pm 3 \sqrt{3}
\end{gather*}
}}

*** Solve a Quadratic Equation with a Perfect Square Trinomial
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525456786
:END:

**** Text

math: Solve $p^2 - 10p + 25 = 18$
{{c1::
\begin{align*}
p^2 - 10p + 25 &= 18 \text{ is a perfect square trinomial} \\
(p - 5)^2 &= 18 \\
p - 5 &= \pm 3 \sqrt{2} \\
p &= 5 \pm 3 \sqrt{2}
\end{align*}
}}

** 10.2 Solve Quadratic Equations by Completing the Square
*** Solve a Quadratic Equation of the Form x^2 + bx + c = 0 by Completing the Square
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525456911
:END:

**** Text

math: Solve $y^2 = 6y + 16$ by completing the square
{{c1::
\begin{gather*}
y^2 = 6y + 16 \\
y^2 - 6y = 16 \\
y^2 - 2 \cdot 3y + 9 = 16 + 9 \\
(y - 3)^2 = 25 \\
y - 3 = \pm \sqrt{25} \\
y - 3 = \pm 5 \\
y = 3 \pm 5 \\
y = -2, y = 8
\end{gather*}
}}

*** Solve a Quadratic Equation of the Form x^2 + bx + c = 0 by Completing the Square with a Coefficient
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525457052
:END:

**** Text

math: Solve $2x^2 - 3x = 20$ by completing the square
{{c1::
\begin{gather*}
2x^2 - 3x = 20 \\
2(x^2 - \frac{3}{2}x) = 20 \\
x^2 - \frac{3}{2}x = 10 \\
x^2 - 2\frac{3}{4}x = 10 \\
x^2 - 2\frac{3}{4}x + \frac{9}{16} = 10 + \frac{9}{16} \\
x^2 - 2\frac{3}{4}x + \frac{9}{16} = \frac{169}{16} \\
(x - \frac{3}{4})^2 = \frac{169}{16} \\
x - \frac{3}{4} = \pm \frac{13}{4} \\
x = \frac{3}{4} \pm \frac{13}{4} \\
x = 4, x = -\frac{5}{2}
\end{gather*}
}}

** 10.3 Solve Quadratic Equations Using the Quadratic Formula
*** Quadratic Formula
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525457190
:END:

**** Text

math: The solution to $ax^2 + bx + c = 0, a \neq 0$ is
{{c1::
\begin{gather*}
x = \frac{ -b \pm \sqrt{b^2 - 4ac} }{2a}
\end{gather*}
}}

*** Derivation of Quadratic Formula
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525457363
:END:

**** Text

math: Derive the Quadratic Formula
{{c1::
\begin{gather*}
\text{Complete the square} \\
ax^2 + bx + c = 0 \\
ax^2 + bx = -c \\
x^2 + \frac{b}{a}x = \frac{-c}{a} \\
x^2 + \frac{b}{a}x + (\frac{1}{2}\frac{b}{a})^2 = \frac{-c}{a} + (\frac{1}{2}\frac{b}{a})^2 \\
x^2 + \frac{b}{a}x + \frac{b^2}{4a^2} = \frac{-c}{a} + \frac{b^2}{4a^2} \\
(x + \frac{b}{2a})^2 = \frac{b^2 - 4ac}{4a^2} \\
\\
\text{Solve for x} \\
x + \frac{b}{2a} = \pm \sqrt{ \frac{b^2 - 4ac}{4a^2} } \\
x + \frac{b}{2a} = \pm \frac{ \sqrt{b^2 - 4ac} }{2a} \\
x = - \frac{b}{2a} \pm \frac{ \sqrt{b^2 - 4ac} }{2a} \\
x = \frac{ -b \pm \sqrt{b^2 - 4ac} }{2a}
\end{gather*}
}}

*** Solve a Quadratic Equation with the Quadratic Formula
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525457495
:END:

**** Text

math: Solve $\frac{1}{2}u^2 + \frac{2}{3}u = \frac{1}{3}$ by using the Quadratic Formula
{{c1::
\begin{gather*}
\text{Remove the fractions by multiplying by the LCD} \\
3u^2 + 4u - 2 = 0 \\
\\
\text{Use the quadratic formula} \\
u = \frac{ -b \pm \sqrt{b^2 - 4ac} }{2a} \\
u = \frac{ -4 \pm \sqrt{16 + 24} }{6} \\
\\
\text{Simplify} \\
u = \frac{ -4 \pm \sqrt{40} }{6} \\
u = \frac{ -4 \pm 2 \sqrt{10} }{6} \\
u = \frac{ -2 \pm \sqrt{10} }{3}
\end{gather*}
}}

*** Quadratic Formula Discriminant
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525457981
:END:

**** Text

math: In the Quadratic Formula, {{c1::$b^2 - 4ac$}} is {{c2::the Discrimant}}

*** Use the Discriminant to Determine the Number of Solutions of a Quadratic Equation
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525458206
:END:

**** Text

math: State the number of solutions of a Quadratic Equation based on its Discriminant values:
- If {{c1::$b^2 - 4ac > 0$, the equation has two solutions}}
- If {{c1::$b^2 - 4ac = 0$, the equation has one solution}}
- If {{c1::$b^2 - 4ac < 0$, the equation has no real solutions}}

**** Extra

The discrimant is the value in the square root in the Quadratic Formula. If it's positive the
Formula has two real solutions. If it's equal to zero the Formula has only one solution. If it's
negative the Formula has no real solutions.

*** Identify the Most Appropriate Method to Solve a Quadratic Equation
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525458383
:END:

**** Text

math: Solve a Quadratic Equation by:
- {{c1::Trying to factor it first}}
- {{c1::Next trying to use the square root property}}
- {{c1::Finally using the quadratic formula}}

** 10.5 Graphing Quadratic Equations in Two Variables
*** Parabola Orientation
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525458612
:END:

**** Text

math: For a Quadratic Equation $y = ax^2 + bx + c$ the parabola opens
- {{c1::Upward if $a > 0$}}
- {{c1::Downward if $a < 0$}}

*** Parabola Vertex
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525458885
:END:

**** Text

math: The {{c1::Vertex}} of a Parabola is {{c2::its highest or lowest}} point

*** Parabola Vertex/Axis of Symmetry
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525459036
:END:

**** Text

math: Parabola's {{c1::Vertex/Axis of Symmetry}} x-coordinate = {{c2::$-\frac{b}{2a}$}}

*** Vertex Example
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525459188
:END:

**** Text

math: For the parabola $y = 3x^2 - 6x + 2$ find the axis of symmetry and the vertex
{{c1::
\begin{gather*}
\text{The axis of symmetry is on the $x$-coordinate of the vertex} \\
x_{vertex} = -\frac{b}{2a} \\
x_{vertex} = -\frac{-6}{6} = 1 \\
\\
\text{Now replace $x$ by $x_{vertex}$ in the equation} \\
y_{vertex} = 3 - 6 + 2 = -1 \\
\\
\text{The Vertex is at (1, -1)}
\end{gather*}
}}

*** Find the Intercepts of a Parabola
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525459337
:END:

**** Text

math:
To find the x-intercepts of a Parabola, {{c1::let y = 0 and solve for x}}
To find the y-intercept  of a Parabola, {{c1::let x = 0 and solve for y}}

*** Intercepts Example
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525459463
:END:

**** Text

math: Find the intercepts of the parabola $y = x^2 - 2x - 8$
{{c1::
\begin{gather*}
\text{For the y-intercept, let x = 0 and solve for y} \\
y = 0^2 - 2*0 - 8 = -8 \\
\text{y-intercept: (0, -8)} \\
\\
\text{For the x-intercept, let y = 0 and solve for x} \\
0 = x^2 - 2x - 8 \\
0 = (x - 4)(x + 2) \\
x = 4, x = -2 \\
\text{x-intercepts: (4, 0), (-2, 0)}
\end{gather*}
}}

*** Use the Discriminant to Determine the Number of x-intercepts of a Parabola
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525459920
:END:

**** Text

math: State the number of x-intercepts of a Parabola based on its Discriminant values:
- If {{c1::$b^2 - 4ac > 0$, the parabola has two x-intercepts}}
- If {{c1::$b^2 - 4ac = 0$, the parabola has one x-intercept}}
- If {{c1::$b^2 - 4ac < 0$, the parabola has no x-intercept}}

*** Minimum or Maximum Values of a Quadratic Equation
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525460083
:END:

**** Text

math: The {{c1::y-coordinate of the vertex}} of the graph of a quadratic equation is the:
- {{c2::minimum value of the equation if the parabola opens upward}}
- {{c2::maximum value of the equation if the parabola opens downward}}

*** Minimum or Maximum Example
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_NOTE_ID: 1626525460224
:END:

**** Text

math: Find the minimum or maximum value of the quadratic equation $y = x^2 + 2x - 8$
{{c1::
\begin{gather*}
\text{$a$ is positive, so the parabola opens upward.} \\
\text{A minimum value is to be found.} \\
\\
\text{The minimum value is at the Vertex} \\
x_{vertex} = -\frac{b}{2a} = -\frac{2}{2} = -1 \\
y_{vertex} = 1 - 2 - 8 = -9 \\
\\
\text{The minimum value is $-9$ and it occurs when $x = -1$}
\end{gather*}
}}
